runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/project/index.html
  upload: dist/project/index.html
- url: /
  static_dir: dist/project

 skip_files:
 - node_modules/
 - src/
 - ^(.*/)?\..*$
 - ^(.*/)?\.*\.json$
 - ^(.*/)?\.*\.md$
 - ^(.*/)?\.*\.yaml$
 - ^LICENSE 

